"""
Generate data/processed/COVERAGE.md from the cached long-history panel.

Why this exists (Phase 11, Task 3, AC-3): coverage must be STATED, not assumed. This
reads the parquet that cache_prices.py --long-history already wrote and its companion
provenance CSV, and reports — per symbol — first bar, last bar, row count, source(s)
and every internal gap longer than a normal market closure. It states explicitly
whether the 2008, 2020 and 2022 episodes are present, which is 11-01's actual success
measure (see the plan's "Goal, stated as a number").

Side-effecting (reads/writes files) — a pipeline, not library code, per src/CLAUDE.md.

Usage:
    python src/pipelines/coverage_report.py
    python src/pipelines/coverage_report.py --tag long_history
"""

import argparse
import pathlib
import sys

import pandas as pd

REPO = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))

from portutils.ingestion.history import find_coverage_gaps  # noqa: E402

PROCESSED_DIR = REPO / "data" / "processed"

# The three regime windows the milestone's claim rests on (v0.4 ROADMAP: "does hedging
# work across MANY historical points and regimes"). A symbol "covers" an episode if it
# has at least one valid bar on or before the window start AND on or after the window
# end — i.e. its own coverage spans the whole episode, not just touches it.
EPISODES = {
    "2008 financial crisis": ("2008-09-01", "2009-03-31"),
    "2020 COVID crash": ("2020-02-15", "2020-04-30"),
    "2022 rate shock": ("2022-01-01", "2022-10-31"),
}


def _episode_covered(series, start, end):
    valid = series.dropna()
    if valid.empty:
        return False
    return valid.index.min() <= pd.Timestamp(start) and valid.index.max() >= pd.Timestamp(end)


def build_coverage_report(prices: pd.DataFrame, provenance: pd.DataFrame = None) -> str:
    """Pure-ish formatter: takes already-loaded frames, returns the Markdown text.
    Split from main() so it can be exercised in tests/test_history.py without a
    parquet on disk.
    """
    lines = [
        "# Coverage report",
        "",
        "Generated by `src/pipelines/coverage_report.py`. States what the cached long-history",
        "panel actually contains — per Phase 11's AC-3, coverage is stated here, not assumed",
        "from row counts alone.",
        "",
        "## Per-symbol coverage",
        "",
        "| Symbol | First bar | Last bar | Rows | Source(s) | Internal gaps (>5 calendar days) |",
        "|---|---|---|---|---|---|",
    ]
    for sym in prices.columns:
        series = prices[sym]
        first = series.first_valid_index()
        last = series.last_valid_index()
        n = int(series.notna().sum())
        if provenance is not None and sym in provenance.columns:
            sources = sorted(provenance[sym].dropna().unique().tolist())
        else:
            sources = ["unknown"]
        gaps = find_coverage_gaps(series)
        gap_text = (
            "; ".join(f"{g[0].date()} to {g[1].date()} ({g[2]}d)" for g in gaps)
            if gaps else "none"
        )
        lines.append(
            f"| {sym} | {first.date() if first is not None else 'n/a'} "
            f"| {last.date() if last is not None else 'n/a'} | {n} "
            f"| {', '.join(sources)} | {gap_text} |"
        )

    lines += ["", "## Regime coverage — the milestone's actual success measure", ""]
    for name, (start, end) in EPISODES.items():
        covered_by = [sym for sym in prices.columns if _episode_covered(prices[sym], start, end)]
        not_covered = [sym for sym in prices.columns if sym not in covered_by]
        status = "COVERED" if covered_by and not not_covered else (
            "PARTIALLY COVERED" if covered_by else "NOT COVERED"
        )
        lines.append(f"- **{name}** ({start} to {end}): **{status}**"
                      f" — covered by: {covered_by or 'none'}"
                      + (f"; missing: {not_covered}" if not_covered else ""))

    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tag", default="long_history")
    args = ap.parse_args()

    prices_path = PROCESSED_DIR / f"prices_{args.tag}.parquet"
    provenance_path = PROCESSED_DIR / f"provenance_{args.tag}.csv"
    if not prices_path.exists():
        raise FileNotFoundError(
            f"{prices_path} not found — run cache_prices.py --long-history first")

    prices = pd.read_parquet(prices_path)
    provenance = pd.read_csv(provenance_path, index_col=0, parse_dates=True) \
        if provenance_path.exists() else None

    report = build_coverage_report(prices, provenance)
    out_path = PROCESSED_DIR / "COVERAGE.md"
    out_path.write_text(report, encoding="utf-8")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
